# site settings
title: TAJY
subtitle: by VnCenturion
email: contato@tajy.com.br
description: Soluções em engenharia, construção civil, incorporação imobiliária,
  projetos técnicos e gestão de obras.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tajy.com.br" # the base hostname & protocol for your site
author: Vinícius Centurión
street_address: Rua Bananeiras, n.361, Sala 101, cxpst 330, manaíra.
city: João Pessoa
state: PB
zip_code: 58038-170
country: Brasil
phone: (83) 99990-1913

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/vncenturion
  Instagram: https://www.instagram.com/tajyconstrucoes/
  LinkedIn: https://www.linkedin.com/company/tajyconstrucoes

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
